sudo: required
language: python
python:
  - "2.7"

cache: pip

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING=False

before_install:
  - sudo apt-get update -qq

install:
  - sudo -H pip install ansible==2.4
  - sudo -H pip install docker-py
  - sudo -H pip install six --upgrade
  - sudo apt-get install -y sshpass
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles

services:
  - docker

script:
  - ansible-playbook -i tests/inventory tests/syntax-check.yml --syntax-check
#  - ansible-playbook -i tests/inventory  tests/docker-centos-bxms-copy.yml

notifications:
  slack: redhat:GhPEcNzYddt4Pf9OJW2wcyCK